/* eslint-disable no-await-in-loop */
import assert from "node:assert/strict"
import { describe, it, before, after } from "node:test"
import { spawn } from "node:child_process"
import { readdirSync, unlinkSync, readFileSync } from "node:fs"
import { createConnection } from "node:net"
import path from "node:path"
import cds from "@sap/cds"
import createHelpers from "../utils/helpers.js"

const SAMPLE_DIR = path.resolve(import.meta.dirname, "../samples/travel")
const TRAVEL_AGENT_DIR = path.join(SAMPLE_DIR, "travel-agent")
const XFLIGHTS_DIR = path.join(SAMPLE_DIR, "xflights")
const LEISURE_DIR = path.join(SAMPLE_DIR, "leisure-services")
const XFLIGHTS_PORT = 4005
const LEISURE_PORT = 4006

let xflightsProc, leisureProc
let reusedXflights = false
let reusedLeisure = false

function cleanupChildren() {
  try {
    xflightsProc?.kill()
  } catch {
    /* ignore */
  }
  try {
    leisureProc?.kill()
  } catch {
    /* ignore */
  }
}

process.on("exit", cleanupChildren)
process.on("SIGINT", () => {
  cleanupChildren()
  process.exit(130)
})

function isPortOpen(port) {
  const tryHost = (host) =>
    new Promise((resolve) => {
      const sock = createConnection({ port, host })
      let done = false
      const finish = (val) => {
        if (done) return
        done = true
        try {
          sock.destroy()
        } catch {
          /* ignore */
        }
        resolve(val)
      }
      sock.once("connect", () => finish(true))
      sock.once("error", () => finish(false))
      setTimeout(() => finish(false), 500)
    })
  return Promise.all([tryHost("127.0.0.1"), tryHost("::1")]).then((rs) => rs.some(Boolean))
}

function startServer(cwd, port, label) {
  return new Promise((resolve, reject) => {
    const proc = spawn("npx", ["cds-serve"], {
      cwd,
      env: { ...process.env, FORCE_COLOR: "false", NODE_ENV: "development" },
      stdio: ["ignore", "pipe", "pipe"],
    })

    let output = ""
    const re = new RegExp(`server listening on \\{[^}]*url:\\s*'http:\\/\\/localhost:${port}'`)

    const timer = setTimeout(() => {
      try {
        proc.kill()
      } catch {
        /* ignore */
      }
      reject(
        new Error(
          `[${label}] Failed to start on port ${port} within 60s.\nOutput tail:\n${output.slice(-2000)}`,
        ),
      )
    }, 60_000)

    const onData = (chunk) => {
      output += chunk.toString()
      if (re.test(output)) {
        clearTimeout(timer)
        proc.stdout.off("data", onData)
        proc.stderr.off("data", onData)
        resolve(proc)
      }
    }

    proc.stdout.on("data", onData)
    proc.stderr.on("data", onData)
    proc.once("exit", (code) => {
      if (code != null && code !== 0) {
        clearTimeout(timer)
        reject(
          new Error(`[${label}] Exited with code ${code}.\nOutput tail:\n${output.slice(-2000)}`),
        )
      }
    })
  })
}

async function stopServer(proc, cwd) {
  if (!proc) return
  if (proc.exitCode == null) {
    proc.kill()
    await Promise.race([
      new Promise((resolve) => proc.once("exit", resolve)),
      new Promise((resolve) => setTimeout(resolve, 5_000)),
    ])
  }
  // Clean up sqlite files generated by the child
  try {
    for (const f of readdirSync(cwd).filter((f) => /^db.*\.sqlite(-shm|-wal)?$/.test(f))) {
      try {
        unlinkSync(path.join(cwd, f))
      } catch {
        /* ignore */
      }
    }
  } catch {
    /* ignore */
  }
}

before(async () => {
  const [xflightsBusy, leisureBusy] = await Promise.all([
    isPortOpen(XFLIGHTS_PORT),
    isPortOpen(LEISURE_PORT),
  ])

  const tasks = []
  if (xflightsBusy) {
    reusedXflights = true
  } else {
    tasks.push(
      startServer(XFLIGHTS_DIR, XFLIGHTS_PORT, "xflights").then((p) => {
        xflightsProc = p
      }),
    )
  }
  if (leisureBusy) {
    reusedLeisure = true
  } else {
    tasks.push(
      startServer(LEISURE_DIR, LEISURE_PORT, "leisure-services").then((p) => {
        leisureProc = p
      }),
    )
  }
  await Promise.all(tasks)
})

after(async () => {
  await Promise.all([
    xflightsProc ? stopServer(xflightsProc, XFLIGHTS_DIR) : Promise.resolve(),
    leisureProc ? stopServer(leisureProc, LEISURE_DIR) : Promise.resolve(),
  ])
})

const { POST, axios, GET } = cds.test(TRAVEL_AGENT_DIR)

async function collectToolCallsFromCheckpoints(threadId) {
  const { BaseCheckpointSaver } = await import("@langchain/langgraph-checkpoint")
  // Use BaseCheckpointSaver's serde to deserialize checkpoint data
  const saver = new (class extends BaseCheckpointSaver {})()
  const serde = saver.serde

  const rows = await SELECT.from("cap.agent.Checkpoints").where({ thread_id: threadId })
  const tools = new Set()

  for (const row of rows) {
    let checkpoint
    try {
      checkpoint = await serde.loadsTyped("json", row.checkpoint)
    } catch {
      continue
    }
    const messages = checkpoint?.channel_values?.messages || []
    for (const msg of messages) {
      const calls = msg?.tool_calls || msg?.kwargs?.tool_calls
      if (Array.isArray(calls)) {
        for (const tc of calls) {
          const name = tc?.name || tc?.function?.name
          if (name) tools.add(name)
        }
      }
    }
  }

  return tools
}

describe("@cap-js/agents - Travel Sample E2E", () => {
  let helpers

  before(async () => {
    helpers = createHelpers({ POST, axios })
  })

  // ─── Smoke test: agent card built from skills/ scan ──────────────
  it("agent card is built from AGENTS.md + skills/ directory", async () => {
    const res = await GET("/a2a/travel-agent/.well-known/agent-card.json")

    assert.strictEqual(
      res.status,
      200,
      `agent-card request failed: ${res.status}\n` +
        `body: ${typeof res.data === "string" ? res.data.slice(0, 500) : JSON.stringify(res.data).slice(0, 500)}`,
    )
    const card = res.data

    assert.strictEqual(card.name, "travel-agent", "card.name should come from AGENTS.md")
    assert.match(card.description, /coordinates hotel bookings/i)
    assert.strictEqual(card.version, "1.0.0")

    const skillIds = card.skills.map((s) => s.id).sort()
    assert.deepStrictEqual(
      skillIds,
      ["file-based-planning", "flight-booking", "itinerary-summary", "trip-planning"],
      `expected four skills from skills/ scan, got: ${JSON.stringify(skillIds)}`,
    )

    const trip = card.skills.find((s) => s.id === "trip-planning")
    assert.match(trip.name, /Trip Planning/i)
    assert.ok(trip.tags.includes("travel"), `expected 'travel' in tags: ${trip.tags}`)
    assert.ok(
      trip.examples.some((e) => /paris/i.test(e)),
      `expected a paris example, got: ${JSON.stringify(trip.examples)}`,
    )

    assert.strictEqual(
      card.skills.find((s) => s.id === "plan"),
      undefined,
      "card should not contain the agentify-mode 'plan' skill",
    )
  })

  // ─── E2E: Plan a Paris trip ──────────────────────────────────────
  it(
    "plans a Paris trip using both xflights MCP and leisure-services A2A",
    { timeout: 5 * 60 * 1000 },
    async () => {
      const { sendMessage } = helpers
      const res = await sendMessage(
        "travel-agent",
        "Plan a weekend trip to Paris with Hotels, Flights and activities. Make sure to use the provided tools to search for Hotels, Flights, and Activities",
      )

      assert.strictEqual(
        res.data.result?.status?.state,
        "completed",
        `Task did not complete:\n${JSON.stringify(res.data, null, 2).slice(0, 2000)}`,
      )

      const text = res.data.result.status.message.parts[0].text
      assert.ok(text && text.length > 0, "response text should be non-empty")
      assert.match(text, /paris/i, "response should mention Paris")
      assert.match(text, /hotel/i, "response should reference hotels (leisure-services)")
      assert.match(
        text,
        /activit|tour|cruise|class|experience|museum/i,
        "response should reference activities (leisure-services)",
      )
      assert.match(
        text,
        /flight|airport|airline|CDG|ORY/i,
        "response should reference flights (xflights MCP)",
      )

      const contextId = res.data.result.contextId
      assert.ok(contextId, "task result must include contextId")

      const threadId = `TravelAgentService:${contextId}`
      const toolNames = await collectToolCallsFromCheckpoints(threadId)

      assert.ok(
        toolNames.size > 0,
        `expected at least one tool call recorded in checkpoints for ${threadId}, got none`,
      )

      assert.ok(
        toolNames.has("hotelservice"),
        `expected 'hotelservice' tool call (leisure-services A2A). Recorded tools: ${[...toolNames].sort().join(", ")}`,
      )
      assert.ok(
        toolNames.has("activityservice"),
        `expected 'activityservice' tool call (leisure-services A2A). Recorded tools: ${[...toolNames].sort().join(", ")}`,
      )

      const mcpToolUsed = ["describe", "query", "bookFlight", "cancelFlight", "call_action"].some(
        (n) => toolNames.has(n),
      )
      assert.ok(
        mcpToolUsed,
        `expected at least one xflights MCP tool call (describe/query/bookFlight/cancelFlight). Recorded tools: ${[...toolNames].sort().join(", ")}`,
      )
    },
  )
})

// ─── File I/O E2E (deep-agent path): upload CSV → read_file → write_file → FilePart ───
describe("@cap-js/agent - File I/O (travel-agent — deep-agent path)", () => {
  let csvBase64
  let savedTaskId
  let savedFileBytesB64

  before(() => {
    csvBase64 = readFileSync(path.join(TRAVEL_AGENT_DIR, "trip-requests.csv")).toString("base64")
  })

  it("agent card reflects per-app fileIO MIME overrides (CSV in / markdown out)", async () => {
    const res = await GET("/a2a/travel-agent/.well-known/agent-card.json")
    assert.strictEqual(res.status, 200, `agent-card request failed: ${res.status}`)
    const card = res.data
    assert.ok(
      Array.isArray(card.defaultInputModes) && card.defaultInputModes.includes("text/csv"),
      `expected text/csv in defaultInputModes; got: ${JSON.stringify(card.defaultInputModes)}`,
    )
    assert.ok(
      Array.isArray(card.defaultOutputModes) &&
        card.defaultOutputModes.includes("text/plain") &&
        card.defaultOutputModes.includes("text/markdown"),
      `expected text/csv in defaultOutputModes; got: ${JSON.stringify(card.defaultOutputModes)}`,
    )
  })

  it(
    "ingests CSV → read_file → write_file('/outputs/alice-plan.md') → emits FilePart artifact",
    { timeout: 5 * 60 * 1000 },
    async () => {
      const res = await POST(`/a2a/travel-agent/`, {
        jsonrpc: "2.0",
        id: 1,
        method: "message/send",
        params: {
          message: {
            kind: "message",
            messageId: cds.utils.uuid(),
            role: "user",
            parts: [
              {
                kind: "text",
                text: "Here is the data for three people. Read the file, then plan the first person's trip — search for flights from Frankfurt to New York, a hotel in New York, and food or culture activities. Save the plan to /outputs/alice-plan.md",
              },
              {
                kind: "file",
                file: { name: "trip-requests.csv", mimeType: "text/csv", bytes: csvBase64 },
              },
            ],
          },
        },
      })

      const result = res.data.result
      assert.strictEqual(
        result?.status?.state,
        "completed",
        `Task did not complete:\n${JSON.stringify(res.data, null, 2).slice(0, 2000)}`,
      )

      savedTaskId = result.id
      const contextId = result.contextId

      // Persisted upload
      const InputFiles = cds.model.definitions["cap.agent.Tasks.inputFiles"]
      const inputs = await cds.run(
        SELECT.from(InputFiles).where({
          "up_.contextId": contextId,
          filename: "trip-requests.csv",
        }),
      )
      assert.equal(inputs.length, 1, "expected the uploaded CSV to be persisted")
      assert.equal(inputs[0].mimeType, "text/csv")

      // FilePart artifact emitted from /outputs/
      const filePart = (result.artifacts || [])
        .flatMap((a) => a.parts || [])
        .find((p) => p.kind === "file" && /alice/i.test(p.file?.name || ""))
      assert.ok(filePart, "expected an itinerary FilePart artifact for Alice")
      savedFileBytesB64 = filePart.file.bytes
      const decoded = Buffer.from(filePart.file.bytes, "base64").toString("utf-8")
      // Loose content checks — LLM phrasing varies.
      assert.match(decoded.toLowerCase(), /alice/, "itinerary should mention the traveller")
      assert.match(
        decoded.toLowerCase(),
        /flight|hotel|activit/,
        "itinerary should reference at least one booked domain",
      )

      // Output file persisted in CDS
      const OutputFiles = cds.model.definitions["cap.agent.Tasks.outputFiles"]
      const outputs = await cds.run(SELECT.from(OutputFiles).where({ up__taskId: savedTaskId }))
      assert.ok(outputs.length >= 1, "expected at least one output file row")

      // Tool-call witness: deepagents' built-in read_file + write_file fired.
      const threadId = `TravelAgentService:${contextId}`
      const toolNames = await collectToolCallsFromCheckpoints(threadId)
      assert.ok(
        toolNames.has("read_file"),
        `expected read_file tool call. Recorded tools: ${[...toolNames].sort().join(", ")}`,
      )
      assert.ok(
        toolNames.has("write_file"),
        `expected write_file tool call. Recorded tools: ${[...toolNames].sort().join(", ")}`,
      )
    },
  )

  it("tasks/get returns the same FilePart artifact (round-trip persistence check)", async () => {
    assert.ok(
      savedTaskId,
      "Previous test must have populated savedTaskId — was it skipped or did it fail?",
    )
    const res = await POST(`/a2a/travel-agent/`, {
      jsonrpc: "2.0",
      id: 2,
      method: "tasks/get",
      params: { id: savedTaskId },
    })
    const result = res.data.result
    assert.ok(result, `tasks/get returned no result: ${JSON.stringify(res.data).slice(0, 500)}`)
    assert.strictEqual(result.id, savedTaskId)
    assert.strictEqual(result.status?.state, "completed")
    const filePart = (result.artifacts || [])
      .flatMap((a) => a.parts || [])
      .find((p) => p.kind === "file" && /alice/i.test(p.file?.name || ""))
    assert.ok(filePart, "expected the FilePart to round-trip through tasks/get")
    assert.equal(
      filePart.file.bytes.length,
      savedFileBytesB64.length,
      "round-tripped FilePart byte count should match the originally emitted artifact",
    )
  })

  it(
    "graceful response when reading uploaded file from a fresh conversation (no-file probe)",
    { timeout: 2 * 60 * 1000 },
    async () => {
      // No file part, no contextId → server generates a fresh contextId →
      // no /uploads/ entry exists → UploadsBackend.read returns "not found".
      const res = await POST(`/a2a/travel-agent/`, {
        jsonrpc: "2.0",
        id: 3,
        method: "message/send",
        params: {
          message: {
            kind: "message",
            messageId: cds.utils.uuid(),
            role: "user",
            parts: [
              {
                kind: "text",
                text: "Please read_file('/uploads/trip-requests.csv') and tell me what's in it.",
              },
            ],
          },
        },
      })
      const result = res.data.result
      assert.ok(
        ["completed", "input-required"].includes(result.status.state),
        `expected graceful state, got: ${result.status.state}`,
      )
      const text = (result.status.message?.parts || []).map((p) => p.text || "").join(" ")
      assert.match(
        text.toLowerCase(),
        /not found|no .* file|empty|doesn't|does not|don't|do not|upload|provide/,
        "agent should acknowledge missing file or ask user to upload",
      )
    },
  )
})
