/* eslint-disable no-await-in-loop */
import assert from "node:assert/strict"
import { describe, it, before, after } from "node:test"
import { spawn } from "node:child_process"
import { readdirSync, unlinkSync } from "node:fs"
import { createConnection } from "node:net"
import path from "node:path"
import cds from "@sap/cds"
import createHelpers from "../utils/helpers.js"

const SAMPLE_DIR = path.resolve(import.meta.dirname, "../travel-sample")
const TRAVEL_AGENT_DIR = path.join(SAMPLE_DIR, "travel-agent")
const XFLIGHTS_DIR = path.join(SAMPLE_DIR, "xflights")
const LEISURE_DIR = path.join(SAMPLE_DIR, "leisure-services")
const XFLIGHTS_PORT = 4005
const LEISURE_PORT = 4006

let canLoadDeepagents = true
try {
  import.meta.resolve("deepagents")
} catch {
  canLoadDeepagents = false
}

let xflightsProc, leisureProc
let reusedXflights = false
let reusedLeisure = false

function cleanupChildren() {
  try {
    xflightsProc?.kill()
  } catch {
    /* ignore */
  }
  try {
    leisureProc?.kill()
  } catch {
    /* ignore */
  }
}

process.on("exit", cleanupChildren)
process.on("SIGINT", () => {
  cleanupChildren()
  process.exit(130)
})

function isPortOpen(port) {
  const tryHost = (host) =>
    new Promise((resolve) => {
      const sock = createConnection({ port, host })
      let done = false
      const finish = (val) => {
        if (done) return
        done = true
        try {
          sock.destroy()
        } catch {
          /* ignore */
        }
        resolve(val)
      }
      sock.once("connect", () => finish(true))
      sock.once("error", () => finish(false))
      setTimeout(() => finish(false), 500)
    })
  return Promise.all([tryHost("127.0.0.1"), tryHost("::1")]).then((rs) => rs.some(Boolean))
}

function startServer(cwd, port, label) {
  return new Promise((resolve, reject) => {
    const proc = spawn("npx", ["cds-serve"], {
      cwd,
      env: { ...process.env, FORCE_COLOR: "false", NODE_ENV: "development" },
      stdio: ["ignore", "pipe", "pipe"],
    })

    let output = ""
    const re = new RegExp(`server listening on \\{[^}]*url:\\s*'http:\\/\\/localhost:${port}'`)

    const timer = setTimeout(() => {
      try {
        proc.kill()
      } catch {
        /* ignore */
      }
      reject(
        new Error(
          `[${label}] Failed to start on port ${port} within 60s.\nOutput tail:\n${output.slice(-2000)}`,
        ),
      )
    }, 60_000)

    const onData = (chunk) => {
      output += chunk.toString()
      if (re.test(output)) {
        clearTimeout(timer)
        proc.stdout.off("data", onData)
        proc.stderr.off("data", onData)
        resolve(proc)
      }
    }

    proc.stdout.on("data", onData)
    proc.stderr.on("data", onData)
    proc.once("exit", (code) => {
      if (code != null && code !== 0) {
        clearTimeout(timer)
        reject(
          new Error(`[${label}] Exited with code ${code}.\nOutput tail:\n${output.slice(-2000)}`),
        )
      }
    })
  })
}

async function stopServer(proc, cwd) {
  if (!proc) return
  if (proc.exitCode == null) {
    proc.kill()
    await Promise.race([
      new Promise((resolve) => proc.once("exit", resolve)),
      new Promise((resolve) => setTimeout(resolve, 5_000)),
    ])
  }
  // Clean up sqlite files generated by the child
  try {
    for (const f of readdirSync(cwd).filter((f) => /^db.*\.sqlite(-shm|-wal)?$/.test(f))) {
      try {
        unlinkSync(path.join(cwd, f))
      } catch {
        /* ignore */
      }
    }
  } catch {
    /* ignore */
  }
}

before(async () => {
  if (!canLoadDeepagents) return

  const [xflightsBusy, leisureBusy] = await Promise.all([
    isPortOpen(XFLIGHTS_PORT),
    isPortOpen(LEISURE_PORT),
  ])

  const tasks = []
  if (xflightsBusy) {
    reusedXflights = true
  } else {
    tasks.push(
      startServer(XFLIGHTS_DIR, XFLIGHTS_PORT, "xflights").then((p) => {
        xflightsProc = p
      }),
    )
  }
  if (leisureBusy) {
    reusedLeisure = true
  } else {
    tasks.push(
      startServer(LEISURE_DIR, LEISURE_PORT, "leisure-services").then((p) => {
        leisureProc = p
      }),
    )
  }
  await Promise.all(tasks)
})

after(async () => {
  await Promise.all([
    xflightsProc ? stopServer(xflightsProc, XFLIGHTS_DIR) : Promise.resolve(),
    leisureProc ? stopServer(leisureProc, LEISURE_DIR) : Promise.resolve(),
  ])
})

const { POST, axios, GET } = cds.test(TRAVEL_AGENT_DIR)

async function collectToolCallsFromCheckpoints(threadId) {
  const { BaseCheckpointSaver } = await import("@langchain/langgraph-checkpoint")
  // Use BaseCheckpointSaver's serde to deserialize checkpoint data
  const saver = new (class extends BaseCheckpointSaver {})()
  const serde = saver.serde

  const rows = await SELECT.from("cap.agent.Checkpoints").where({ thread_id: threadId })
  const tools = new Set()

  for (const row of rows) {
    let checkpoint
    try {
      checkpoint = await serde.loadsTyped("json", row.checkpoint)
    } catch {
      continue
    }
    const messages = checkpoint?.channel_values?.messages || []
    for (const msg of messages) {
      const calls = msg?.tool_calls || msg?.kwargs?.tool_calls
      if (Array.isArray(calls)) {
        for (const tc of calls) {
          const name = tc?.name || tc?.function?.name
          if (name) tools.add(name)
        }
      }
    }
  }

  return tools
}

describe("@cap-js/agent - Travel Sample E2E", { skip: !canLoadDeepagents }, () => {
  let helpers

  before(async () => {
    helpers = createHelpers({ POST, axios })
  })

  // ─── Smoke test: agent card built from skills/ scan ──────────────
  it("agent card is built from AGENTS.md + skills/ directory", async () => {
    const res = await GET("/a2a/travel-agent/.well-known/agent-card.json")

    assert.strictEqual(
      res.status,
      200,
      `agent-card request failed: ${res.status}\n` +
        `body: ${typeof res.data === "string" ? res.data.slice(0, 500) : JSON.stringify(res.data).slice(0, 500)}`,
    )
    const card = res.data

    assert.strictEqual(card.name, "travel-agent", "card.name should come from AGENTS.md")
    assert.match(card.description, /coordinates hotel bookings/i)
    assert.strictEqual(card.version, "1.0.0")

    const skillIds = card.skills.map((s) => s.id).sort()
    assert.deepStrictEqual(
      skillIds,
      ["flight-booking", "itinerary-summary", "trip-planning"],
      `expected three skills from skills/ scan, got: ${JSON.stringify(skillIds)}`,
    )

    const trip = card.skills.find((s) => s.id === "trip-planning")
    assert.match(trip.name, /Trip Planning/i)
    assert.ok(trip.tags.includes("travel"), `expected 'travel' in tags: ${trip.tags}`)
    assert.ok(
      trip.examples.some((e) => /paris/i.test(e)),
      `expected a paris example, got: ${JSON.stringify(trip.examples)}`,
    )

    assert.strictEqual(
      card.skills.find((s) => s.id === "plan"),
      undefined,
      "card should not contain the agentify-mode 'plan' skill",
    )
  })

  // ─── E2E: Plan a Paris trip ──────────────────────────────────────
  it(
    "plans a Paris trip using both xflights MCP and leisure-services A2A",
    { timeout: 5 * 60 * 1000 },
    async () => {
      const { sendMessage } = helpers
      const res = await sendMessage(
        "travel-agent",
        "Plan a weekend trip to Paris with Hotels, Flights and activities. Make sure to use the provided tools to search for Hotels, Flights, and Activities",
      )

      assert.strictEqual(
        res.data.result?.status?.state,
        "completed",
        `Task did not complete:\n${JSON.stringify(res.data, null, 2).slice(0, 2000)}`,
      )

      const text = res.data.result.status.message.parts[0].text
      assert.ok(text && text.length > 0, "response text should be non-empty")
      assert.match(text, /paris/i, "response should mention Paris")
      assert.match(text, /hotel/i, "response should reference hotels (leisure-services)")
      assert.match(
        text,
        /activit|tour|cruise|class|experience|museum/i,
        "response should reference activities (leisure-services)",
      )
      assert.match(
        text,
        /flight|airport|airline|CDG|ORY/i,
        "response should reference flights (xflights MCP)",
      )

      const contextId = res.data.result.contextId
      assert.ok(contextId, "task result must include contextId")

      const threadId = `TravelAgentService:${contextId}`
      const toolNames = await collectToolCallsFromCheckpoints(threadId)

      assert.ok(
        toolNames.size > 0,
        `expected at least one tool call recorded in checkpoints for ${threadId}, got none`,
      )

      assert.ok(
        toolNames.has("hotelservice"),
        `expected 'hotelservice' tool call (leisure-services A2A). Recorded tools: ${[...toolNames].sort().join(", ")}`,
      )
      assert.ok(
        toolNames.has("activityservice"),
        `expected 'activityservice' tool call (leisure-services A2A). Recorded tools: ${[...toolNames].sort().join(", ")}`,
      )

      const mcpToolUsed = ["describe", "query", "bookFlight", "cancelFlight", "call_action"].some(
        (n) => toolNames.has(n),
      )
      assert.ok(
        mcpToolUsed,
        `expected at least one xflights MCP tool call (describe/query/bookFlight/cancelFlight). Recorded tools: ${[...toolNames].sort().join(", ")}`,
      )
    },
  )
})
