import { createMiddleware, DynamicStructuredTool } from "langchain"
import { checkAuthorization } from "@cap-js/mcp/lib/auth.js"
import { getFilteredActions } from '../../utils/utils.js'

/**
 * Middleware that filters the tool list passed to the model on every call.
 * The graph is cached once with all tools; this middleware trims it to the
 * subset the current user is authorized to see (checkAuthorization runs per-request).
 */
export function toolAuthMiddleware() {
  // Names of tools generated by generateTools for this service.
  // Anything else (MCP tools, sub-agent tools, file tools) is always passed through.
  return createMiddleware({
    name: "ToolAuthMiddleware",
    wrapModelCall: (request, handler) => {
      if (!request.tools?.length) return handler(request)

      const filtered = request.tools.map((t) => {
        return t.filtered? t.filtered() : t
      }).filter(Boolean)

      return handler({ ...request, tools: filtered })
    },
  })
}

/**
 * Build the set of tool names that generateTools may produce for a service.
 * generateTools uses TOOL_PREFIX="" so names are: "query", "describe", "call",
 * and per-action tools use the action's local name directly.
 */
function _collectCdsToolNames(srv) {
  const names = new Set(["query", "describe", "call"])
  for (const localName of Object.keys(getFilteredActions(srv))) {
    names.add(localName)
  }
  return names
}

/**
 * Decide whether a specific CDS-generated tool name is allowed for the current user.
 */
function _isCdsToolAllowed(name, allowedEntities, allowedActions) {
  if (name === "query") return allowedEntities.size > 0
  if (name === "describe") return allowedEntities.size > 0 || allowedActions.size > 0
  if (name === "call") return allowedActions.size > 0
  // Per-action tool
  return allowedActions.has(name)
}
