name: "Integration tests"
description: "Run tests with BTP services being bound"
inputs:
  CF_ORG:
    description: "Cloud Foundry organization"
    required: true
  CF_SPACE:
    description: "Cloud Foundry space"
    required: true
  NODE_VERSION:
    description: "Node.js version to use for tests"
    required: true
  CDS_VERSION:
    description: "CDS version to use for tests"
    required: true
  NPM_REGISTRY_TOKEN:
    description: "Auth token for internal npm registry"
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup CF CLI and authenticate
      uses: cap/.github/.github/actions/cf-setup@613c5b00ff920ae7d880af4534c83a727900da9e # main
      with:
        org: ${{ inputs.CF_ORG }}
        space: ${{ inputs.CF_SPACE }}

    - name: Use Node.js ${{ inputs.NODE_VERSION }}
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: ${{ inputs.NODE_VERSION }}

    - name: Configure internal registry
      shell: bash
      run: |
        echo "@cap-js:registry=https://int.repositories.cloud.sap/artifactory/api/npm/build-releases-npm/" >> .npmrc
        echo "//int.repositories.cloud.sap/artifactory/api/npm/build-releases-npm/:_authToken=${{ inputs.NPM_REGISTRY_TOKEN }}" >> .npmrc

    - name: Install global CDS
      shell: bash
      run: npm i -g @sap/cds-dk@${{ inputs.CDS_VERSION }}
    - name: Install all dependencies
      shell: bash
      run: npm install --legacy-peer-deps

    - name: CDS Versions being used
      shell: bash
      run: cds v -i

    # Bind AI Core service for hybrid executor
    - name: Bind AI Core
      shell: bash
      run: cds bind -2 joule-cap-proxy -o package.json

    # Run tests in hybrid mode (injects bound credentials into process)
    - name: Run tests in hybrid mode
      shell: bash
      run: cds bind --exec -- npm run test:hybrid
