name: BlackDuck Scans

on:
  workflow_dispatch:
  schedule:
    # Only run twice a week on default branch (main).
    # BlackDuck has a min-scan-interval of 24h:
    - cron: "40 10 * * 3,5"

jobs:
  scans:
    uses: cap/.github/.github/workflows/scans.yml@a10b981add83215f0e5fb043670ac1547950199b # main
    secrets: inherit
    with:
      project: CDSUMBRELLA
