name: BlackDuck Scans

on:
  workflow_dispatch:
  schedule:
    # Only run twice a week on default branch (main).
    # BlackDuck has a min-scan-interval of 24h:
    - cron: "40 10 * * 3,5"

jobs:
  scans:
    uses: cap/.github/.github/workflows/scans.yml@613c5b00ff920ae7d880af4534c83a727900da9e # main
    secrets: inherit
    with:
      project: CDSUMBRELLA
