name: Check Changelog
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]
    branches:
      - main
jobs:
  Check-Changelog:
    name: Check Changelog Action
    runs-on: [self-hosted, solinas]
    steps:
      - name: Check changelog
        uses: cap/.github/.github/actions/check-changelog@613c5b00ff920ae7d880af4534c83a727900da9e # main
