name: Check Changelog
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]
    branches:
      - main
jobs:
  Check-Changelog:
    name: Check Changelog Action
    runs-on: [self-hosted, solinas]
    steps:
      - name: Check changelog
        uses: cap/.github/.github/actions/check-changelog@5507e8e09411e392cc3e81bacd6773358c1d6b24 # main
