name: Check Changelog
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]
    branches:
      - main
jobs:
  Check-Changelog:
    name: Check Changelog Action
    runs-on: [self-hosted, solinas]
    steps:
      - name: Check changelog
        uses: cap/.github/.github/actions/check-changelog@725cb63379e2e73f163abfa7d77f12ec7c1e1a81 # main
