name: Check PR Title
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  Check-PR-Title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: cap-js/.github/.github/actions/check-pr-title@main
