name: Check PR Title
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  Check-PR-Title:
    name: Validate PR Title
    runs-on: [self-hosted, solinas]
    steps:
      - name: Check PR title
        uses: cap/.github/.github/actions/check-pr-title@613c5b00ff920ae7d880af4534c83a727900da9e # main
