name: Check PR Title
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  Check-PR-Title:
    name: Validate PR Title
    runs-on: [self-hosted, solinas]
    steps:
      - name: Check PR title
        uses: cap/.github/.github/actions/check-pr-title@725cb63379e2e73f163abfa7d77f12ec7c1e1a81 # main
