name: Create Github Release

on:
  push:
    tags:
      - "rel/*"

jobs:
  create-github-release:
    uses: cap/.github/.github/workflows/create-gh-release.yml@f52abfb84ed361d807bc7c3613df7955bc719275 # main
    secrets: inherit
