name: Create Github Release

on:
  push:
    tags:
      - "rel/*"

jobs:
  create-github-release:
    uses: cap/.github/.github/workflows/create-gh-release.yml@a10b981add83215f0e5fb043670ac1547950199b # main
    secrets: inherit
