name: Create Github Release

on:
  push:
    tags:
      - "rel/*"

jobs:
  create-github-release:
    uses: cap/.github/.github/workflows/create-gh-release.yml@613c5b00ff920ae7d880af4534c83a727900da9e # main
    secrets: inherit
