name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  test:
    runs-on: [self-hosted, solinas]
    timeout-minutes: 10
    name: SQLite Tests with Node.js ${{ matrix.node-version }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x, 24.x]
        cds-version: [latest]
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configure internal registry
        run: |
          echo "@cap-js:registry=https://int.repositories.cloud.sap/artifactory/api/npm/build-releases-npm/" >> .npmrc
          echo "//int.repositories.cloud.sap/artifactory/api/npm/build-releases-npm/:_authToken=${{ secrets.NPM_REGISTRY_TOKEN }}" >> .npmrc
      - run: npm i -g @sap/cds-dk@${{ matrix.cds-version }}
      - run: npm i
      - run: cd tests/bookshop && npm i
      - run: npm run test

  test-hybrid:
    runs-on: [self-hosted, solinas-medium]
    container:
      image: public.int.repositories.cloud.sap/ubuntu:24.04
    name: Hybrid Tests with Node.js ${{ matrix.node-version }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x, 24.x]
        cds-version: [latest]
    env:
      CF_USERNAME: ${{ secrets.CF_USERNAME }}
      CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
    steps:
      - run: apt-get update -y && apt-get install make -y
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: cap/.github/.github/actions/git-setup@main
        with:
          com-github-token: ${{ secrets.COM_GITHUB_TOKEN }}
      - name: Run hybrid integration tests
        uses: ./.github/actions/integration-tests
        with:
          CF_ORG: ${{ secrets.CF_ORG }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
          NODE_VERSION: ${{ matrix.node-version }}
          CDS_VERSION: ${{ matrix.cds-version }}
          NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
