name: Metadata Validator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validation:
    name: Agent Card
    runs-on: [self-hosted, solinas]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
      - name: Configure internal registry
        run: |
          echo "@cap-js:registry=https://int.repositories.cloud.sap/artifactory/api/npm/build-releases-npm/" >> .npmrc
          echo "//int.repositories.cloud.sap/artifactory/api/npm/build-releases-npm/:_authToken=${{ secrets.NPM_REGISTRY_TOKEN }}" >> .npmrc
      - run: npm i -g @sap/cds-dk
      - run: npm i
      - run: cd tests/samples/bookshop && cds compile ./srv -s CatalogService -2 a2a > agent-card.json
      - name: Run API Metadata Validator
        uses: CPA/api-metadata-validator@fc6eed1120508c0ffc59516def4167e90b4c7686 # main
        with:
          files: ./tests/samples/bookshop/*-card.json
          verbose: true
          only-changed-files: false
